"""Metric explanations for Lynx Real Estate Analysis."""

from __future__ import annotations
from lynx_realestate.models import MetricExplanation

METRIC_EXPLANATIONS: dict[str, MetricExplanation] = {}

def _add(key, full_name, description, why_used, formula, category):
    METRIC_EXPLANATIONS[key] = MetricExplanation(key=key, full_name=full_name, description=description,
                                                  why_used=why_used, formula=formula, category=category)

# ---------------------------------------------------------------------------
# Valuation
# ---------------------------------------------------------------------------
_add("pe_trailing", "Price-to-Earnings Ratio (TTM)", "Compares stock price to trailing 12-month earnings per share.", "Of limited use for REITs because GAAP earnings are depressed by large non-cash depreciation on real estate. Use P/FFO or P/AFFO as the primary valuation lens instead.", "P/E = Price / EPS (TTM)", "valuation")
_add("pe_forward", "Price-to-Earnings Ratio (Forward)", "P/E based on forward 12-month consensus EPS.", "Same caveats as trailing P/E for REITs; still useful to gauge earnings trajectory and compare against non-REIT peers.", "Forward P/E = Price / Forward EPS", "valuation")
_add("pb_ratio", "Price-to-Book Ratio", "Compares stock price to GAAP book value per share.", "Distorted for REITs because real estate is held at cost less depreciation, not fair value. Compare to P/NAV which uses market value of properties.", "P/B = Price / Book Value per Share", "valuation")
_add("ps_ratio", "Price-to-Sales Ratio", "Compares market cap to revenue (rental income).", "Useful for cross-REIT comparison of how the market prices each dollar of rent. Interpret alongside NOI margin.", "P/S = Market Cap / Revenue", "valuation")
_add("p_fcf", "Price-to-Free Cash Flow", "Compares market cap to free cash flow.", "Less central than P/AFFO for REITs; FCF definitions vary widely with capitalized capex. AFFO is the cleaner cash metric.", "P/FCF = Market Cap / Free Cash Flow", "valuation")
_add("ev_ebitda", "Enterprise Value / EBITDA", "Capital-structure-neutral valuation multiple.", "Useful for REITs since it neutralizes varying leverage. EV/EBITDA 15-20x is typical for quality REITs; lower for higher-risk property types.", "EV/EBITDA = (Market Cap + Debt - Cash) / EBITDA", "valuation")
_add("ev_revenue", "Enterprise Value / Revenue", "Compares enterprise value to rental revenue.", "Complement to EV/EBITDA. High multiples typical for data centers and cell towers; lower for office and retail.", "EV/Revenue = EV / Revenue", "valuation")
_add("peg_ratio", "PEG Ratio", "P/E adjusted for earnings growth rate.", "Rarely used in REIT analysis because of earnings distortion. Prefer FFO growth vs P/FFO multiple.", "PEG = P/E / Annual EPS Growth Rate", "valuation")
_add("dividend_yield", "Dividend Yield", "Annual dividend as a percentage of share price.", "Central REIT metric — REITs distribute most taxable income. Compare yield to the 10-year Treasury and check AFFO payout coverage for sustainability.", "Yield = Annual Dividends / Price", "valuation")
_add("earnings_yield", "Earnings Yield", "Inverse of the P/E ratio.", "Compare to the 10-year Treasury yield. For REITs, FFO yield is more meaningful than earnings yield.", "Earnings Yield = EPS / Price", "valuation")
_add("price_to_tangible_book", "Price / Tangible Book", "Price vs tangible book value per share.", "Less relevant for REITs because real estate is tangible but held at historical cost. Use P/NAV for a fair-value comparison.", "P/TBV = Price / (Equity - Intangibles) / Shares", "valuation")
_add("price_to_ncav", "Price / NCAV (Net-Net)", "Price vs net current asset value per share.", "Rarely meets Graham's criterion for REITs — most assets are long-term property, not current. Useful only in special distressed situations.", "P/NCAV = Price / (Current Assets - Total Liabilities) / Shares", "valuation")
_add("cash_to_market_cap", "Cash-to-Market-Cap Ratio", "How much of market cap is backed by cash.", "REITs typically hold little cash (distribute most earnings). High cash may signal an imminent acquisition or capital raise underway.", "Cash / Market Cap = Total Cash / Market Capitalization", "valuation")
_add("fcf_yield", "FCF Yield", "Free cash flow as a percentage of enterprise value.", "Useful cross-sector anchor, but AFFO yield is more consistent for REITs because it normalizes recurring capex.", "FCF Yield = Free Cash Flow / Enterprise Value", "valuation")
_add("nav_per_share", "Net Asset Value Per Share", "Estimated fair value of the real estate portfolio minus debt, divided by shares.", "Primary valuation anchor for REITs. Trading at a discount to NAV suggests undervaluation; a persistent premium implies growth expectations or scarcity value.", "NAV/Share = (Property Fair Value - Net Debt) / Shares", "intrinsic_value")
_add("p_ffo", "Price / Funds From Operations", "Market price per share divided by FFO per share.", "The REIT equivalent of P/E. 15-20x is typical for quality REITs; data centers and towers trade at 25-30x, retail and office often 10-15x.", "P/FFO = Price / FFO per Share", "valuation")
_add("p_affo", "Price / Adjusted FFO", "Price per share divided by AFFO per share.", "Most rigorous REIT valuation — AFFO subtracts recurring maintenance capex, representing true distributable cash. Preferred over P/FFO by sophisticated REIT investors.", "P/AFFO = Price / AFFO per Share", "valuation")
_add("p_nav", "Price / Net Asset Value", "Market cap vs estimated NAV.", "A premium to NAV implies the market values the REIT's platform, growth pipeline, or management above the underlying property values. A discount often signals distress or weak sentiment.", "P/NAV = Market Cap / NAV", "valuation")
_add("implied_cap_rate", "Implied Cap Rate", "NOI divided by enterprise value — the cap rate implied by the current market price.", "Compare to private-market transaction cap rates for the same property type. Higher implied cap rate than the private market = REIT trading cheap.", "Implied Cap Rate = NOI / Enterprise Value", "valuation")
_add("ffo_yield", "FFO Yield", "FFO per share divided by price.", "Inverse of P/FFO. Use alongside dividend yield to see how much FFO is retained for growth vs distributed to shareholders.", "FFO Yield = FFO per Share / Price", "valuation")

# ---------------------------------------------------------------------------
# Profitability
# ---------------------------------------------------------------------------
_add("roe", "Return on Equity", "Profit generated per dollar of equity.", "Depressed for REITs by non-cash depreciation. Track the trend rather than absolute level; use FFO-based returns for a fairer read.", "ROE = Net Income / Equity", "profitability")
_add("roa", "Return on Assets", "Profit per dollar of assets.", "Low by design for REITs given asset-heavy balance sheets. Use NOI / gross assets as the real-estate equivalent.", "ROA = Net Income / Total Assets", "profitability")
_add("roic", "Return on Invested Capital", "Return on all invested capital.", "Useful to compare how well different REIT management teams allocate capital across acquisitions and developments.", "ROIC = NOPAT / Invested Capital", "profitability")
_add("gross_margin", "Gross Margin", "Revenue remaining after direct property operating costs.", "For REITs, roughly equivalent to NOI margin. High gross margin = efficient property operations and favorable expense recoveries.", "Gross Margin = Gross Profit / Revenue", "profitability")
_add("operating_margin", "Operating Margin", "Revenue remaining after all operating expenses.", "Measures the combined efficiency of property operations plus corporate G&A. Scale advantage shows up here.", "Operating Margin = Operating Income / Revenue", "profitability")
_add("net_margin", "Net Profit Margin", "Revenue remaining as net profit.", "Heavily distorted by depreciation and one-time property gains/losses for REITs. Prefer FFO margin.", "Net Margin = Net Income / Revenue", "profitability")
_add("fcf_margin", "Free Cash Flow Margin", "Revenue converted to free cash flow.", "Shows actual cash generation. AFFO margin is the REIT-specific equivalent and is more comparable across peers.", "FCF Margin = FCF / Revenue", "profitability")
_add("ebitda_margin", "EBITDA Margin", "Revenue remaining as EBITDA.", "Typically 60-70% for quality REITs — very high by cross-sector standards due to the fixed-cost nature of real estate.", "EBITDA Margin = EBITDA / Revenue", "profitability")
_add("croci", "Cash Return on Capital Invested", "Operating cash flow as a return on invested capital.", "Avoids distortion from large non-cash real estate depreciation. A cleaner read on REIT capital efficiency than ROIC.", "CROCI = Operating Cash Flow / (Total Assets - Cash)", "profitability")
_add("ocf_to_net_income", "OCF / Net Income Ratio", "How much of reported earnings converts to actual cash.", "Usually well above 1.0 for REITs because depreciation suppresses net income. Declines in this ratio can signal earnings-quality issues.", "OCF/NI = Operating Cash Flow / |Net Income|", "profitability")
_add("noi", "Net Operating Income", "Rental and related revenue minus property operating expenses.", "The fundamental building block of REIT profitability. Unburdened by corporate overhead, financing, or depreciation — the clean property-level cash profit.", "NOI = Rental Revenue - Property Operating Expenses", "profitability")
_add("noi_margin", "NOI Margin", "NOI as a percentage of rental revenue.", "Benchmark within property type: 65-70% for apartments, 70-80% for office/industrial, 90%+ for net-lease. Trending margin signals operational efficiency.", "NOI Margin = NOI / Rental Revenue", "profitability")
_add("ffo", "Funds From Operations", "Net income plus real estate depreciation, excluding gains on property sales.", "The industry-standard REIT earnings measure, defined by NAREIT. Adds back non-cash depreciation that distorts GAAP earnings for property-heavy businesses.", "FFO = Net Income + Real Estate Depreciation - Gains on Sale", "profitability")
_add("ffo_per_share", "FFO Per Share", "Funds From Operations allocated per share.", "REIT equivalent of EPS. Consistent FFO/share growth is the primary driver of REIT total return.", "FFO/Share = FFO / Weighted Avg Shares", "profitability")
_add("affo", "Adjusted Funds From Operations", "FFO minus recurring maintenance capex and straight-line rent adjustments.", "The best single REIT cash-earnings measure — represents cash truly available for distribution after keeping the portfolio leasable.", "AFFO = FFO - Recurring Capex - Straight-line Rent Adj", "profitability")
_add("affo_per_share", "AFFO Per Share", "Adjusted FFO allocated per share.", "The numerator of the AFFO payout ratio and P/AFFO. Growth in AFFO/share is the purest signal of REIT value creation.", "AFFO/Share = AFFO / Weighted Avg Shares", "profitability")
_add("ffo_margin", "FFO Margin", "FFO as a percentage of revenue.", "Useful cross-REIT comparison normalized for size. Declining FFO margin may indicate rising leverage cost or operating issues.", "FFO Margin = FFO / Revenue", "profitability")
_add("same_store_noi_growth", "Same-Store NOI Growth", "NOI growth from properties owned in both comparison periods.", "The cleanest organic growth signal — strips out the effect of acquisitions, dispositions, and developments. 2-4% is typical; >5% is strong.", "SS NOI Growth = (Current SS NOI - Prior SS NOI) / Prior SS NOI", "profitability")
_add("occupancy_rate", "Occupancy Rate", "Percentage of leasable area that is leased.", "Leading indicator of NOI trajectory. 95%+ is strong for apartments/industrial; 85-90% is healthy for office; net-lease REITs target 99%+.", "Occupancy = Leased Area / Total Leasable Area", "profitability")

# ---------------------------------------------------------------------------
# Solvency
# ---------------------------------------------------------------------------
_add("debt_to_equity", "Debt-to-Equity Ratio", "Debt financing vs equity financing.", "REITs run high D/E by design (often 0.8-1.5x). Rising D/E over time can flag weakening credit quality and refinancing risk.", "D/E = Total Debt / Equity", "solvency")
_add("debt_to_ebitda", "Debt / EBITDA", "Years of EBITDA needed to repay debt.", "Primary REIT leverage metric tracked by rating agencies. Investment-grade REITs target 5-6x; above 7x signals refinancing stress.", "Debt/EBITDA = Total Debt / EBITDA", "solvency")
_add("current_ratio", "Current Ratio", "Short-term asset coverage of liabilities.", "Less informative for REITs because most assets are long-term properties. Focus on liquidity (undrawn revolver + cash) and the debt maturity schedule instead.", "Current Ratio = Current Assets / Current Liabilities", "solvency")
_add("quick_ratio", "Quick Ratio", "Liquidity excluding inventory.", "Secondary liquidity check for REITs. The weighted-average debt maturity and upcoming refinancing wall are more diagnostic.", "Quick Ratio = (Current Assets - Inventory) / Current Liabilities", "solvency")
_add("interest_coverage", "Interest Coverage", "Ability to pay interest from operating earnings.", "Investment-grade REITs target >3x; <2x signals distress. Matters more in rising-rate environments as maturities reprice higher.", "Interest Coverage = Operating Income / Interest Expense", "solvency")
_add("altman_z_score", "Altman Z-Score", "Bankruptcy probability predictor.", "Less reliable for REITs because of high intentional leverage and low reported earnings. Use as a rough screen only.", "Z = 1.2(WC/TA) + 1.4(RE/TA) + 3.3(EBIT/TA) + 0.6(MV/TL) + 1.0(Sales/TA)", "solvency")
_add("net_debt", "Net Debt", "Total debt minus cash and equivalents.", "The true leverage figure used for EV, Net Debt/EBITDA, and implied cap rate. Cash buffer matters less for REITs given distribution requirements.", "Net Debt = Total Debt - Total Cash", "solvency")
_add("total_debt", "Total Debt", "All interest-bearing obligations on the balance sheet.", "Compare to gross asset value (debt-to-assets) and watch the maturity ladder for near-term refinancing exposure.", "Total Debt = Short-term Debt + Long-term Debt", "solvency")
_add("total_cash", "Total Cash and Equivalents", "Cash on the balance sheet.", "Most REITs run thin cash and rely on revolvers. Cash spikes often precede acquisitions, developments, or distribution cuts.", "Total Cash = Cash + Equivalents + Short-term Investments", "solvency")
_add("cash_runway_years", "Cash Runway", "Years of operation covered by cash at the current burn rate.", "Not typically meaningful for cash-generating REITs. Flag if negative AFFO leaves the REIT dependent on external capital.", "Cash Runway = Total Cash / Annual Burn Rate", "solvency")
_add("working_capital", "Working Capital", "Current assets minus current liabilities.", "Secondary for REITs. A large negative balance can be normal (accruals of distributions payable) — read alongside the maturity schedule.", "Working Capital = Current Assets - Current Liabilities", "solvency")
_add("cash_per_share", "Cash Per Share", "Cash allocated per share.", "Minor for REITs. More relevant when there's a pending acquisition or dividend reset.", "Cash/Share = Total Cash / Shares Outstanding", "solvency")
_add("tangible_book_value", "Tangible Book Value", "Equity minus intangibles.", "For REITs, tangible book is basically the depreciated cost of properties. NAV (fair-value based) is a more useful benchmark.", "TBV = Total Equity - Intangible Assets - Goodwill", "solvency")
_add("ncav", "Net Current Asset Value", "Current assets minus total liabilities.", "Rarely applicable to REITs since the bulk of value is long-term property, not current assets.", "NCAV = Current Assets - Total Liabilities", "solvency")
_add("ncav_per_share", "NCAV Per Share", "Net current asset value per share.", "Graham's net-net benchmark, generally not meaningful for REITs.", "NCAV/Share = (Current Assets - Total Liabilities) / Shares", "solvency")
_add("debt_per_share", "Debt Per Share", "Total debt allocated per share.", "Compares leverage at the shareholder level over time. Rising debt/share without corresponding AFFO/share growth is a warning sign.", "Debt/Share = Total Debt / Shares Outstanding", "solvency")
_add("net_debt_per_share", "Net Debt Per Share", "Net debt allocated per share.", "The leverage portion of each share's claim. Compare to NAV/share to judge how much of equity value is levered.", "Net Debt/Share = Net Debt / Shares Outstanding", "solvency")
_add("debt_service_coverage", "Debt Service Coverage", "Ability to service total debt service from operating cash flow.", "Tighter than interest coverage — captures principal amortization. REIT lenders typically require DSCR >1.25x at the property level.", "DSC = Operating Cash Flow / Total Debt Service", "solvency")
_add("debt_to_gross_assets", "Debt / Gross Assets", "Total debt divided by gross (undepreciated) real estate assets.", "The REIT-specific leverage ratio, preferred to debt/equity because book equity understates true asset value. 40-50% is typical; >60% is aggressive.", "Debt/Gross Assets = Total Debt / Gross Real Estate Assets", "solvency")
_add("fixed_charge_coverage", "Fixed Charge Coverage", "Coverage of interest plus preferred dividends and ground rent.", "A stricter coverage metric for REITs with preferred stock or ground leases. Bond covenants typically require >1.5x.", "FCC = EBITDA / (Interest + Preferred Dividends + Ground Rent)", "solvency")
_add("weighted_avg_debt_maturity", "Weighted Average Debt Maturity", "Average years until debt comes due, weighted by balance.", "Longer maturities reduce refinancing risk. Quality REITs ladder maturities at 6-8+ years. A wall of maturities inside 2 years is a red flag in rising-rate markets.", "WADM = Sum(Debt_i * Years_i) / Total Debt", "solvency")
_add("pct_fixed_rate_debt", "% Fixed-Rate Debt", "Share of total debt with fixed interest rates.", "Fixed-rate protects the REIT from rate spikes. 80%+ fixed is conservative; <60% exposes distributions to rate risk.", "% Fixed = Fixed-Rate Debt / Total Debt", "solvency")

# ---------------------------------------------------------------------------
# Growth
# ---------------------------------------------------------------------------
_add("revenue_growth_yoy", "Revenue Growth (YoY)", "Annual revenue (rental income) change.", "Combines organic same-store growth plus acquisitions minus dispositions. Decompose to judge the quality of growth.", "Growth = (Rev_Current - Rev_Prior) / |Rev_Prior|", "growth")
_add("revenue_cagr_3y", "Revenue CAGR (3-Year)", "3-year compound revenue growth.", "Smooths acquisition lumpiness. 5-10% is healthy for a growing REIT; stable net-lease REITs may sit at 2-4%.", "CAGR = (End/Start)^(1/3) - 1", "growth")
_add("revenue_cagr_5y", "Revenue CAGR (5-Year)", "5-year compound revenue growth.", "Captures a full real-estate cycle. Use to distinguish durable platforms from acquisition-fueled spikes.", "CAGR = (End/Start)^(1/5) - 1", "growth")
_add("earnings_growth_yoy", "Earnings Growth (YoY)", "Annual net income change.", "Noisy for REITs due to property-sale gains and depreciation. FFO growth is the preferred signal.", "Growth = (NI_Current - NI_Prior) / |NI_Prior|", "growth")
_add("earnings_cagr_3y", "Earnings CAGR (3-Year)", "3-year compound net income growth.", "Reference figure for cross-sector comparison; FFO CAGR is more meaningful within the REIT universe.", "CAGR = (End/Start)^(1/3) - 1", "growth")
_add("earnings_cagr_5y", "Earnings CAGR (5-Year)", "5-year compound net income growth.", "Long-run earnings trajectory. Expect volatility from property gains/losses; normalize with FFO.", "CAGR = (End/Start)^(1/5) - 1", "growth")
_add("fcf_growth_yoy", "FCF Growth (YoY)", "Annual free cash flow change.", "Shows the trend in cash generation. Capex lumpiness can distort; AFFO growth is smoother.", "Growth = (FCF_Current - FCF_Prior) / |FCF_Prior|", "growth")
_add("book_value_growth_yoy", "Book Value Growth (YoY)", "Annual growth in book value per share.", "Understates true value creation for REITs because of depreciation. NAV/share growth is the relevant equivalent.", "Growth = (BV/Share Current - BV/Share Prior) / BV/Share Prior", "growth")
_add("dividend_growth_5y", "Dividend Growth (5-Year CAGR)", "5-year compound growth of the dividend.", "Dividend Aristocrat REITs grow 3-6%/yr through the cycle. Growth must be funded by AFFO growth — check coverage.", "5Y Div Growth = (Div_End / Div_Start)^(1/5) - 1", "growth")
_add("shares_growth_yoy", "Share Dilution (YoY)", "Annual change in shares outstanding.", "REITs frequently issue equity to fund acquisitions. 3-5%/yr is typical; >10%/yr is heavy dilution unless matched by accretive deployment.", "Dilution = (Shares_Current - Shares_Prior) / Shares_Prior", "growth")
_add("shares_growth_3y_cagr", "Dilution CAGR (3-Year)", "3-year compound share dilution rate.", "Shows the persistent pace of equity issuance. If AFFO/share isn't rising alongside, issuance is destroying per-share value.", "CAGR = (Shares_End / Shares_Start)^(1/3) - 1", "growth")
_add("fully_diluted_shares", "Fully Diluted Shares", "Basic shares plus convertible securities, warrants, and OP units.", "REITs often have substantial operating-partnership units convertible into common shares — always analyze on a fully diluted basis.", "Fully Diluted = Basic Shares + Convertibles + Warrants + OP Units", "share_structure")
_add("dilution_ratio", "Dilution Ratio", "Fully diluted shares divided by basic shares.", "A ratio >1.10 indicates significant potential dilution from OP units, warrants, or convertibles. Check trigger conditions.", "Dilution Ratio = Fully Diluted Shares / Basic Shares", "growth")
_add("capex_to_revenue", "Capex / Revenue", "Capital expenditure as a percentage of revenue.", "REIT capex has two components — maintenance (recurring) and development/redevelopment. Break out both; development capex drives future NOI growth.", "Capex % = |Capital Expenditure| / Revenue", "growth")
_add("capex_to_ocf", "Capex / Operating Cash Flow", "Capital spending relative to cash generation.", ">70% leaves little room for distributions; <30% may indicate underinvestment in the portfolio. Development-heavy REITs often run higher.", "Capex/OCF = |Capital Expenditure| / Operating Cash Flow", "growth")
_add("reinvestment_rate", "Reinvestment Rate", "Capital expenditure as a percentage of EBITDA.", "Shows development intensity. Externally growing REITs rely on reinvestment + equity issuance — check incremental returns on capex.", "Reinvestment = |Capex| / EBITDA", "growth")
_add("dividend_payout_ratio", "Dividend Payout Ratio (GAAP)", "Dividends divided by GAAP net income.", "Misleading for REITs (often >100% of net income because of depreciation). Always translate into AFFO payout for coverage assessment.", "Payout = |Dividends| / Net Income", "growth")
_add("dividend_coverage", "Dividend Coverage (FCF)", "How many times FCF covers the dividend.", "General coverage check. For REITs, AFFO coverage is the precise measure — must exceed 1.0x for the distribution to be self-funded.", "Coverage = Free Cash Flow / |Dividends Paid|", "growth")
_add("shareholder_yield", "Shareholder Yield", "Total cash returned to shareholders as a percentage of market cap.", "Combines dividends + buybacks. REIT buybacks are rare since most cash is distributed — dividend yield dominates here.", "Yield = (Dividends + Buybacks) / Market Cap", "growth")
_add("fcf_per_share", "FCF Per Share", "Free cash flow allocated per share.", "The trend line is the key read. Rising FCF/share despite equity issuance confirms value-accretive deployment.", "FCF/Share = Free Cash Flow / Shares Outstanding", "growth")
_add("ocf_per_share", "OCF Per Share", "Operating cash flow allocated per share.", "Base cash-generating power before capital-allocation decisions. Growing OCF/share indicates rental income is outpacing dilution.", "OCF/Share = Operating Cash Flow / Shares Outstanding", "growth")
_add("ffo_growth_yoy", "FFO Growth (YoY)", "Annual growth in Funds From Operations.", "Core REIT growth signal. 5-8% FFO growth is strong; acceleration often precedes multiple expansion.", "Growth = (FFO_Current - FFO_Prior) / |FFO_Prior|", "growth")
_add("ffo_cagr_3y", "FFO CAGR (3-Year)", "3-year compound FFO growth.", "Smooths acquisition timing. Best single measure of management's ability to compound earnings power.", "CAGR = (FFO_End / FFO_Start)^(1/3) - 1", "growth")
_add("affo_growth_yoy", "AFFO Growth (YoY)", "Annual growth in Adjusted FFO.", "Cleaner than FFO growth because it includes maintenance capex. AFFO growth is the precondition for sustainable distribution growth.", "Growth = (AFFO_Current - AFFO_Prior) / |AFFO_Prior|", "growth")
_add("distribution_growth_5y", "Distribution Growth (5-Year)", "5-year CAGR of distributions/dividends per share.", "REITs emphasize distribution growth for income-focused investors. 3-6%/yr is typical; sustained distribution growth requires matching AFFO/share growth.", "5Y Growth = (Dist_End / Dist_Start)^(1/5) - 1", "growth")
_add("same_store_noi_growth_yoy", "Same-Store NOI Growth (YoY)", "Annual NOI growth from properties held throughout both periods.", "The purest organic growth metric for REITs — shows pricing power, occupancy trends, and expense control stripped of acquisitions.", "SS NOI Growth = (Current SS NOI - Prior SS NOI) / Prior SS NOI", "growth")
_add("acquisition_growth_yoy", "Acquisition Growth (YoY)", "Growth in assets or NOI attributable to acquisitions.", "External growth lever. Evaluate alongside the spread between acquisition cap rates and cost of capital — value creation requires the spread to be positive.", "Acq Growth = Acquisition NOI / Prior Year NOI", "growth")
_add("affo_payout_ratio", "AFFO Payout Ratio", "Distributions divided by AFFO.", "The single most important dividend-safety metric for REITs. <80% is safe; 80-95% is tight; >100% means the payout is unsustainable without external capital.", "AFFO Payout = Distributions / AFFO", "growth")
_add("ffo_payout_ratio", "FFO Payout Ratio", "Distributions divided by FFO.", "Secondary coverage gauge. Always looks lower than AFFO payout because FFO doesn't deduct recurring capex. 70-85% is typical.", "FFO Payout = Distributions / FFO", "growth")

# ---------------------------------------------------------------------------
# Efficiency
# ---------------------------------------------------------------------------
_add("asset_turnover", "Asset Turnover", "Revenue divided by total assets.", "Low for REITs by design (0.1-0.2x). Trend matters more than the absolute level — improving turnover signals rising rents or better occupancy.", "Asset Turnover = Revenue / Total Assets", "efficiency")
_add("inventory_turnover", "Inventory Turnover", "Cost of sales divided by inventory.", "Not meaningful for rental REITs. Only relevant for homebuilders and REITs that hold properties held-for-sale.", "Inventory Turnover = COGS / Inventory", "efficiency")
_add("receivables_turnover", "Receivables Turnover", "Revenue divided by receivables.", "Rent-collection efficiency. Falling turnover can signal tenant credit stress — a leading indicator of NOI problems.", "Receivables Turnover = Revenue / Accounts Receivable", "efficiency")
_add("days_sales_outstanding", "Days Sales Outstanding", "Average days to collect rent.", "30-45 days typical. Extended DSO often flags tenant delinquencies or troubled collections.", "DSO = 365 / Receivables Turnover", "efficiency")
_add("days_inventory", "Days Inventory Outstanding", "Average days inventory is held.", "Not meaningful for typical REITs; relevant only for build-to-sell or condo-converter REITs.", "DIO = 365 / Inventory Turnover", "efficiency")
_add("cash_conversion_cycle", "Cash Conversion Cycle", "Days from paying suppliers to collecting from tenants.", "Generally short or negative for REITs since rent is collected in advance. A widening cycle signals operational issues.", "CCC = DSO + DIO - DPO", "efficiency")
_add("fcf_conversion", "FCF / EBITDA Conversion", "How efficiently EBITDA converts to free cash flow.", "Tends to be low for REITs because of capex and cash interest. 30-50% is typical; net-lease REITs run higher.", "FCF Conversion = Free Cash Flow / EBITDA", "efficiency")
_add("capex_intensity", "Capex Intensity", "Capital expenditure as a share of revenue.", "Separate maintenance vs growth capex. Self-storage and net-lease have low intensity (<5%); hotels and lab space run much higher.", "Intensity = |Capex| / Revenue", "efficiency")
_add("g_and_a_as_pct_of_revenue", "G&A as % of Revenue", "Corporate overhead relative to revenue.", "Measures platform efficiency. 4-6% is typical for large REITs; >10% flags bloated overhead relative to the asset base.", "G&A % = G&A Expense / Revenue", "efficiency")

# ---------------------------------------------------------------------------
# Share Structure
# ---------------------------------------------------------------------------
_add("shares_outstanding", "Shares Outstanding", "Total basic shares outstanding.", "Baseline for dilution tracking. Compare against historical counts to see the pace of equity issuance.", "Shares Outstanding = Basic Shares at Period End", "share_structure")
_add("warrants_outstanding", "Warrants Outstanding", "Total warrants that can convert to shares.", "Less common in REITs than in small-cap equities; when present, check strike prices relative to market price.", "Warrants Outstanding = Warrant Count", "share_structure")
_add("options_outstanding", "Options Outstanding", "Employee stock options outstanding.", "Track executive-compensation dilution. Heavy option grants at below-NAV prices are value-destructive.", "Options Outstanding = Stock Option Count", "share_structure")
_add("insider_ownership_pct", "Insider Ownership", "Percentage of shares held by officers, directors, and founders.", ">5% insider ownership is strong alignment for REITs; founder-led REITs often exceed 10-15%. Externally managed REITs typically show low insider stakes — a structural concern.", "Insider % = Insider Shares / Shares Outstanding", "share_structure")
_add("institutional_ownership_pct", "Institutional Ownership", "Percentage held by institutional investors.", "REITs have high institutional ownership (60-90%) due to inclusion in REIT indices and dedicated REIT funds. Low institutional % suggests a lack of index inclusion.", "Institutional % = Institutional Shares / Shares Outstanding", "share_structure")
_add("float_shares", "Float Shares", "Shares available for public trading.", "Low float can amplify price volatility. REITs with <30% float struggle with index inclusion and institutional adoption.", "Float = Shares Outstanding - Restricted Shares", "share_structure")
_add("share_structure_assessment", "Share Structure Assessment", "Qualitative assessment of share structure health.", "Considers dilution pace, insider alignment, OP unit overhang, and float. A clean structure supports multiple re-rating.", "Assessment based on dilution rate + insider % + overhang", "share_structure")
_add("warrant_overhang_risk", "Warrant Overhang Risk", "Risk from outstanding warrants converting to shares.", "In-the-money warrants create a ceiling on share price until exercised. Less relevant for large REITs; a flag for recently formed vehicles.", "Assessment based on warrant count + strike price vs market", "share_structure")

# ---------------------------------------------------------------------------
# Intrinsic Value
# ---------------------------------------------------------------------------
_add("dcf_value", "DCF Fair Value", "Fair value derived from a discounted free cash flow projection.", "DCF inputs for REITs should be AFFO-based with a rent-growth-aware terminal value. Compare the result against NAV and P/AFFO multiple valuations.", "DCF = Sum(FCF_t / (1+r)^t) + Terminal Value", "intrinsic_value")
_add("graham_number", "Graham Number", "Conservative fair value from Graham's formula.", "Useful sanity check but unreliable for REITs due to depreciation distortion. NAV-based approaches are preferred.", "Graham = sqrt(22.5 * EPS * BVPS)", "intrinsic_value")
_add("lynch_fair_value", "Lynch Fair Value", "Peter Lynch-style fair value = EPS * (growth + dividend yield).", "Adapt using FFO growth and dividend yield. Gives a PEG-style REIT valuation anchor.", "Lynch Value = EPS * (Growth Rate + Dividend Yield)", "intrinsic_value")
_add("ncav_value", "NCAV Fair Value", "Net current asset value per share.", "Rarely meaningful for REITs since value resides in long-term real estate, not current assets.", "NCAV = (Current Assets - Total Liabilities) / Shares", "intrinsic_value")
_add("asset_based_value", "Asset-Based Fair Value", "Fair value based on book or tangible asset value.", "For REITs, replace with NAV which marks property to fair value rather than depreciated book cost.", "Asset Value = (Total Assets - Liabilities) / Shares", "intrinsic_value")
_add("ffo_multiple_value", "FFO-Multiple Fair Value", "Fair value from applying a target P/FFO multiple.", "Practical valuation when peer multiples are stable. Use sector-specific multiples (e.g., 20x for industrial vs 12x for office).", "FFO Value = Target P/FFO * FFO per Share", "intrinsic_value")
_add("affo_multiple_value", "AFFO-Multiple Fair Value", "Fair value from applying a target P/AFFO multiple.", "The most rigorous REIT multiple-based valuation — AFFO captures true distributable cash, so the multiple is more comparable across peers.", "AFFO Value = Target P/AFFO * AFFO per Share", "intrinsic_value")
_add("current_price", "Current Market Price", "Latest traded share price.", "Reference point for all margin-of-safety calculations.", "Current Price = Latest Close", "intrinsic_value")
_add("margin_of_safety_dcf", "Margin of Safety (DCF)", "Discount of current price vs DCF fair value.", ">25% margin provides cushion for assumption errors. DCF is sensitive to discount rate — stress test with varying rate environments.", "MoS = (DCF Value - Price) / DCF Value", "intrinsic_value")
_add("margin_of_safety_graham", "Margin of Safety (Graham)", "Discount of price vs Graham number.", "Conservative benchmark, though less reliable for REITs due to earnings distortion.", "MoS = (Graham - Price) / Graham", "intrinsic_value")
_add("margin_of_safety_ncav", "Margin of Safety (NCAV)", "Discount of price vs NCAV.", "Rarely applicable for REITs — most value is in non-current property assets.", "MoS = (NCAV - Price) / NCAV", "intrinsic_value")
_add("margin_of_safety_asset", "Margin of Safety (Asset-Based)", "Discount of price vs asset-based fair value.", "Use NAV-based margin of safety instead for REITs to avoid book-cost distortion.", "MoS = (Asset Value - Price) / Asset Value", "intrinsic_value")
_add("margin_of_safety_nav", "Margin of Safety (NAV)", "Discount of current price to NAV per share.", "The most important margin-of-safety calc for REITs. Trading at 15-25% discount to NAV is historically attractive; a premium to NAV requires growth justification.", "MoS = (NAV - Price) / NAV", "intrinsic_value")
_add("margin_of_safety_ffo", "Margin of Safety (FFO Multiple)", "Discount of current price to FFO-multiple fair value.", "Quick relative-valuation check against peer P/FFO multiples.", "MoS = (FFO Value - Price) / FFO Value", "intrinsic_value")
_add("margin_of_safety_affo", "Margin of Safety (AFFO Multiple)", "Discount of current price to AFFO-multiple fair value.", "The cleanest margin-of-safety gauge for REITs using a cash-based earnings multiple.", "MoS = (AFFO Value - Price) / AFFO Value", "intrinsic_value")

# ---------------------------------------------------------------------------
# Real Estate Quality
# ---------------------------------------------------------------------------
_add("quality_score", "Real Estate Quality Score", "Composite quality score (0-100).", "Evaluates portfolio quality, financial position, management, occupancy, tenant mix, lease duration, and distribution safety. >70 = high quality; <30 = weak.", "Weighted sum of: portfolio quality + occupancy + leverage + distribution coverage + management + diversification", "real_estate_quality")
_add("management_quality", "Management Quality Assessment", "Qualitative read on the management team's track record.", "Track record of accretive capital deployment, dividend growth history, and alignment through ownership. Externally managed structures deserve extra scrutiny.", "Qualitative evaluation of capital allocation and track record", "real_estate_quality")
_add("jurisdiction_assessment", "Jurisdiction Risk Assessment", "Property-market risk by country/region.", "Tier 1 (US, UK, Western Europe, developed Asia) offers deep capital markets and transparent property rights. Tier 3 elevates political and currency risk on rents.", "Tier classification + country-level commentary", "real_estate_quality")
_add("portfolio_quality", "Portfolio Quality", "Quality of the underlying real estate assets.", "Evaluates property class (A/B/C), age, location, and market share within submarkets. Class A in primary markets commands premium cap rates and tenant demand.", "Qualitative assessment of asset class, vintage, and market position", "real_estate_quality")
_add("portfolio_diversification", "Portfolio Diversification", "Diversification across tenants, geographies, and property types.", "Reduces single-tenant and regional risk. Quality REITs limit top-10 tenant exposure to <30% and avoid single-market concentration >20%.", "Concentration scoring by tenant, geography, and asset type", "real_estate_quality")
_add("occupancy_assessment", "Occupancy Assessment", "Qualitative assessment of current and trending occupancy.", "Occupancy level + direction = operational health signal. Rising occupancy in a stable portfolio is the cleanest positive indicator.", "Occupancy level + trend classification", "real_estate_quality")
_add("lease_duration_assessment", "Lease Duration (WALT) Assessment", "Weighted average lease term across the portfolio.", "Longer WALT = higher cash-flow visibility. Net-lease REITs target 10+ years; apartment REITs run 1-year leases. Assess WALT against property-type norms.", "WALT = Sum(Remaining Term * Annual Rent) / Total Annual Rent", "real_estate_quality")
_add("tenant_concentration", "Tenant Concentration", "Concentration risk in top tenants.", "Top-10 tenants ideally <30%; single-tenant exposure above 10% is a risk factor. Credit rating of top tenants matters for distribution safety.", "Top-N Tenant % = Rent from Top-N / Total Rent", "real_estate_quality")
_add("same_store_noi_trend", "Same-Store NOI Trend", "Multi-year trend in same-store NOI growth.", "Consistent positive SS NOI growth confirms pricing power and operational execution. Sustained negative trends are a yellow flag for the asset class or management.", "Multi-year SS NOI growth trajectory", "real_estate_quality")
_add("cap_rate_assessment", "Cap Rate Assessment", "Implied cap rate vs private-market transaction cap rates.", "Implied cap > private market = stock cheap vs NAV. Implied cap < private market = public premium (often justified by platform value or growth).", "Implied Cap Rate vs Private Market Cap Rates", "real_estate_quality")
_add("financial_position", "Financial Position", "Overall balance-sheet strength.", "Evaluates leverage, debt maturity ladder, rate exposure, liquidity, and credit rating. Investment-grade REITs access capital on better terms through cycles.", "Composite of leverage + coverage + maturity + rating", "real_estate_quality")
_add("dilution_risk", "Dilution Risk", "Risk from future share issuance.", "REITs habitually issue equity. Dilution is acceptable when new capital earns above the cost of capital — issuance below NAV destroys value.", "Historical dilution pace + pipeline funding needs", "real_estate_quality")
_add("catalyst_density", "Catalyst Density", "Frequency of near-term value-creation catalysts.", "Development deliveries, redevelopment, lease-up, and accretive acquisitions drive FFO/share growth. High catalyst density supports multiple expansion.", "Count and quality of announced catalysts in next 12-18 months", "real_estate_quality")
_add("strategic_backing", "Strategic Backing", "Support from strategic partners, sponsors, or parent companies.", "External sponsorship provides deal flow and capital access. Joint ventures with institutional partners signal asset quality.", "Qualitative assessment of sponsor/partner ecosystem", "real_estate_quality")
_add("competitive_position", "Competitive Position", "Market position within the property sub-sector.", "Scale advantages in REITs show up as lower G&A per property, better tenant relationships, and preferred access to acquisition pipelines.", "Market share + scale + barriers-to-entry assessment", "real_estate_quality")
_add("asset_backing", "Asset Backing", "Value of tangible real estate vs market cap.", "Hard-asset backing differentiates REITs from other equities. A discount to replacement cost offers a margin of safety in down cycles.", "Qualitative: gross real estate value vs market cap", "real_estate_quality")
_add("niche_position", "Niche Position", "Position in a specialized property niche.", "Specialty REITs (data centers, cell towers, life sciences) often enjoy structural demand tailwinds and higher multiples than diversified peers.", "Qualitative read on niche demand drivers", "real_estate_quality")
_add("insider_alignment", "Insider Alignment", "Degree of insider ownership and skin in the game.", "Founder-led REITs with significant insider stakes tend to allocate capital more conservatively. Externally managed REITs often show structural misalignment.", "Insider ownership % + alignment mechanisms", "real_estate_quality")
_add("revenue_predictability", "Revenue Predictability", "Stability and visibility of rental revenue.", "Long WALT, staggered expirations, and high-credit tenants create predictable revenue. Net-lease REITs have the most predictable revenue streams.", "WALT + tenant credit + lease structure assessment", "real_estate_quality")

# ---------------------------------------------------------------------------
# Market Intelligence
# ---------------------------------------------------------------------------
_add("net_insider_shares_3m", "Net Insider Buys (3M)", "Net shares bought by insiders over the trailing 3 months.", "Insider buying at REITs is a strong positive signal since insiders understand NAV better than outsiders. Positive net buys near 52-week lows is particularly bullish.", "Net Insider Shares = Buys - Sells (last 90 days)", "market_intelligence")
_add("insider_buy_signal", "Insider Buy Signal", "Qualitative flag on recent insider activity.", "Clustered insider purchases by multiple executives often precede NAV revisions or accretive acquisitions.", "Signal derived from size + breadth + timing of purchases", "market_intelligence")
_add("institutions_pct", "Institutional Ownership %", "Percentage held by institutional investors.", "REITs typically show 60-90% institutional ownership. Meaningful changes flag index rebalancing or conviction shifts among REIT-focused funds.", "Institutional % = Institutional Shares / Shares Outstanding", "market_intelligence")
_add("analyst_count", "Analyst Count", "Number of sell-side analysts covering the stock.", "Low coverage (<5) can mean inefficient pricing opportunities in small/mid-cap REITs. High coverage signals institutional relevance.", "Count of distinct analysts with active ratings", "market_intelligence")
_add("recommendation", "Analyst Recommendation", "Consensus analyst recommendation.", "Useful as a sentiment gauge only. Analyst downgrades often lag NAV discounts, so insider buying + price discount tends to be a stronger signal.", "Consensus rating (Buy/Hold/Sell)", "market_intelligence")
_add("target_mean", "Mean Price Target", "Average 12-month analyst price target.", "Compare to NAV per share. When the target is below NAV, analysts see execution risk; when above NAV, they see platform/growth value.", "Mean of all analyst targets", "market_intelligence")
_add("target_upside_pct", "Price Target Upside (%)", "Upside to the consensus price target.", "Reference only; NAV-based margin of safety is a stronger anchor for REITs.", "Upside = (Target Mean - Current Price) / Current Price", "market_intelligence")
_add("short_pct_of_float", "Short Interest (% of Float)", "Short interest as a percentage of float.", "REITs can attract shorts when leverage is high, refinancing walls loom, or property-type sentiment turns. >10% short is elevated.", "Short % = Shares Short / Float", "market_intelligence")
_add("short_squeeze_risk", "Short Squeeze Risk", "Qualitative flag on short-squeeze potential.", "High short interest plus low float plus a positive NAV catalyst can trigger squeezes. Rare but meaningful for small-cap REITs.", "Derived from short % + float + days-to-cover", "market_intelligence")
_add("price_current", "Current Price", "Latest market price.", "Input for all valuation ratios and margin-of-safety calculations.", "Current Price = Latest Close", "market_intelligence")
_add("price_52w_high", "52-Week High", "Highest price over the trailing 52 weeks.", "Reference for momentum; distance from highs indicates where the market is in the REIT cycle.", "Max(Daily Close, last 252 trading days)", "market_intelligence")
_add("price_52w_low", "52-Week Low", "Lowest price over the trailing 52 weeks.", "Near the 52-week low with supportive NAV can indicate an entry point; confirm with insider activity and coverage.", "Min(Daily Close, last 252 trading days)", "market_intelligence")
_add("pct_from_52w_high", "% from 52-Week High", "Percentage below the 52-week high.", ">20% below highs often coincides with REIT-cycle lows — check the NAV discount and dividend safety.", "% = (Current - 52W High) / 52W High", "market_intelligence")
_add("price_52w_range_position", "52-Week Range Position", "Current price position within the 52-week range (0-100%).", "Values near 0 indicate compressed valuations; near 100 indicate momentum/premium.", "Position = (Price - 52W Low) / (52W High - 52W Low)", "market_intelligence")
_add("sma_50", "50-Day Simple Moving Average", "Average closing price over the last 50 trading days.", "Short-term trend marker. Price above the 50-SMA signals positive short-term momentum.", "SMA_50 = Avg(Close, last 50 days)", "market_intelligence")
_add("sma_200", "200-Day Simple Moving Average", "Average closing price over the last 200 trading days.", "Long-term trend marker. Price above the 200-SMA confirms a long-term uptrend.", "SMA_200 = Avg(Close, last 200 days)", "market_intelligence")
_add("above_sma_50", "Above 50-SMA?", "Whether price is above the 50-day moving average.", "Short-term trend confirmation. Combine with volume and fundamentals rather than trading off alone.", "Boolean: Current Price > SMA_50", "market_intelligence")
_add("above_sma_200", "Above 200-SMA?", "Whether price is above the 200-day moving average.", "Long-term trend confirmation. Below 200-SMA during a rate-up cycle is common for rate-sensitive REITs.", "Boolean: Current Price > SMA_200", "market_intelligence")
_add("golden_cross", "Golden Cross", "Whether the 50-SMA has crossed above the 200-SMA.", "Technical trend signal. REIT golden crosses often follow rate-cut cycles as yield-sensitive flows return.", "Boolean: SMA_50 > SMA_200 (recent cross)", "market_intelligence")
_add("beta", "Beta", "Volatility relative to the broader market.", "REITs typically run beta 0.7-1.0. Rising-rate episodes temporarily elevate beta as REITs are repriced as bond proxies.", "Beta = Cov(Stock, Market) / Var(Market)", "market_intelligence")
_add("volume_trend", "Volume Trend", "Trend in trading volume.", "Rising volume on advances confirms strength; rising volume on declines confirms distribution. REITs see volume spikes around quarterly NOI prints.", "Current Volume vs 10-day/30-day averages", "market_intelligence")
_add("projected_dilution_annual_pct", "Projected Annual Dilution %", "Forecast annual share issuance from ATM programs and development funding.", "REITs often run at-the-market offerings. 2-4%/yr is normal for externally-growing REITs; issuance below NAV is value-destructive.", "Projected % = (Projected New Shares) / Current Shares", "market_intelligence")
_add("financing_warning", "Financing Warning", "Flag on near-term financing needs.", "REITs with large maturity walls + high leverage + depressed share prices may be forced into dilutive offerings or asset sales.", "Flag derived from maturity ladder + liquidity + market conditions", "market_intelligence")
_add("benchmark_rate_name", "Benchmark Rate (Name)", "Name of the relevant benchmark interest rate (e.g., 10Y US Treasury).", "REITs are highly rate-sensitive. The 10-year Treasury is the most relevant benchmark for REIT discount rates and dividend-yield comparison.", "Identifier of the tracked benchmark rate", "market_intelligence")
_add("benchmark_rate_value", "Benchmark Rate (Value)", "Current value of the benchmark interest rate.", "Compare dividend yield to the 10-year yield for relative attractiveness. Rising benchmarks pressure REIT multiples; falling benchmarks support them.", "Current Rate (%)", "market_intelligence")
_add("sector_etf_name", "Sector ETF Name", "Name of the relevant sector ETF (e.g., VNQ).", "Sector-ETF performance serves as a REIT-cycle proxy. Under/outperformance vs the ETF isolates company-specific alpha.", "Name of relevant real-estate sector ETF", "market_intelligence")
_add("sector_etf_ticker", "Sector ETF Ticker", "Ticker of the relevant sector ETF (e.g., VNQ, IYR).", "Used for relative-performance benchmarking and peer context.", "Ticker of relevant real-estate sector ETF", "market_intelligence")


# ---------------------------------------------------------------------------
# Section and conclusion explanations
# ---------------------------------------------------------------------------
SECTION_EXPLANATIONS = {
    "profile": {"title": "Company Profile", "description": "Company identification, market cap tier, REIT stage (pre-development through stabilized / net-lease), primary property type, and jurisdiction risk."},
    "valuation": {"title": "Valuation Metrics", "description": "Price-based ratios including REIT-specific measures (P/FFO, P/AFFO, P/NAV, implied cap rate) alongside traditional metrics. NAV-based valuations replace book-based approaches for REITs."},
    "profitability": {"title": "Profitability Metrics", "description": "Margin and return analysis including REIT-specific measures (NOI, FFO, AFFO, occupancy, same-store NOI growth). GAAP earnings are distorted by depreciation and gain-on-sale accounting — FFO/AFFO are the primary earnings signals."},
    "solvency": {"title": "Solvency & Balance Sheet", "description": "Balance-sheet strength including REIT-specific measures (debt/gross assets, fixed-charge coverage, weighted-avg maturity, % fixed-rate debt). Maturity ladder and rate exposure are critical given REIT leverage levels."},
    "growth": {"title": "Growth & Distributions", "description": "Revenue, FFO, AFFO, and distribution growth, plus share dilution tracking. Organic (same-store) vs acquisition-driven growth is decomposed. AFFO payout ratio is the core distribution-safety metric."},
    "share_structure": {"title": "Share Structure", "description": "Analysis of basic vs fully diluted shares (including OP units), insider ownership, institutional holdings, and dilution risk. UPREIT structures require fully diluted analysis."},
    "real_estate_quality": {"title": "Real Estate Quality Assessment", "description": "Stage-appropriate quality scoring across portfolio quality, occupancy, lease duration, tenant concentration, same-store NOI trend, cap-rate positioning, financial position, and management alignment."},
    "intrinsic_value": {"title": "Intrinsic Value Estimates", "description": "Multiple valuation methods including REIT-specific approaches: NAV per share, P/FFO multiple value, and P/AFFO multiple value. DCF and Graham methods are provided as sanity checks."},
    "market_intelligence": {"title": "Market Intelligence", "description": "Insider activity, institutional holdings, analyst coverage, short interest, price technicals, projected dilution, rate/macro context, and sector-ETF performance."},
    "conclusion": {"title": "Assessment Conclusion", "description": "Weighted scoring across categories with weights adapted by tier and stage. Includes a screening checklist of REIT-specific quality criteria."},
}

CONCLUSION_METHODOLOGY = {
    "overall": {"title": "Conclusion Methodology", "description": "Score is a weighted average of categories (valuation, profitability, solvency, growth, real-estate quality). Weights vary by both tier and stage. Stabilized/net-lease REITs emphasize distribution safety and NAV discount; development-stage REITs emphasize financial position and execution risk. Verdicts: Strong Buy (>=75), Buy (>=60), Hold (>=45), Caution (>=30), Avoid (<30)."},
    "valuation": {"title": "Valuation Score", "description": "Starts at 50. Adjusted by P/FFO, P/AFFO, P/NAV, implied cap rate vs private market, and dividend yield. Pre-revenue stages de-emphasize cash-flow multiples."},
    "solvency": {"title": "Solvency Score", "description": "Starts at 50. Debt/gross assets, fixed-charge coverage, weighted-avg debt maturity, and % fixed-rate debt drive the score. Near-term maturity walls are penalized heavily, as is interest coverage < 2x."},
    "real_estate_quality": {"title": "Real Estate Quality Score", "description": "Composite of portfolio quality, occupancy, lease duration (WALT), tenant concentration, same-store NOI trend, cap-rate positioning, financial position, management alignment, and insider ownership."},
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def get_explanation(key):
    return METRIC_EXPLANATIONS.get(key)


def get_section_explanation(section):
    return SECTION_EXPLANATIONS.get(section)


def get_conclusion_explanation(category=None):
    return CONCLUSION_METHODOLOGY.get(category or "overall")


def list_metrics(category=None):
    metrics = list(METRIC_EXPLANATIONS.values())
    return [m for m in metrics if m.category == category] if category else metrics


def list_all_metrics():
    return list(METRIC_EXPLANATIONS.values())
